---
abstract: 'Japanese carrier email class'
author:
  - 'Naoki Tomita <tomita@cpan.org>'
build_requires:
  Email::Address: 0
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Email-Address-JP-Mobile
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Email::Address::Loose: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://svn.coderepos.org/share/lang/perl/Email-Address-JP-Mobile/trunk
version: 0.02
