---
abstract: 'Japanese carrier email class'
author:
  - 'Naoki Tomita <tomita@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Email::Address::JP::Mobile
name: Email-Address-JP-Mobile
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Email::Address::Loose: 0
  Encode: 0
  Encode::JP::Mobile: 0.27
  perl: 5.8.0
resources:
  bugtracker: http://github.com/tomi-ru/Email-Address-JP-Mobile/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/tomi-ru/Email-Address-JP-Mobile
version: 0.08
